name: ef21-hess
channels:
  - defaults
dependencies:
  - tornado=6.4.2
  - platformdirs=4.3.6
  - yaml=0.2.5
  - mkl_fft=1.3.11
  - zeromq=4.3.5
  - freetype=2.12.1
  - cuda-runtime=11.8.0
  - libstdcxx-ng=11.2.0
  - libidn2=2.3.4
  - libcufft=10.9.0.58
  - lcms2=2.16
  - ipython=8.31.0
  - libnpp=11.8.0.86
  - _openmp_mutex=4.5
  - comm=0.2.2
  - blas=1.0
  - expat=2.6.4
  - intel-openmp=2023.1.0
  - exceptiongroup=1.2.2
  - llvm-openmp=14.0.6
  - libgcc-ng=14.2.0
  - openjpeg=2.5.2
  - zstd=1.5.6
  - pickleshare=0.7.5
  - pure_eval=0.2.3
  - lz4-c=1.9.4
  - charset-normalizer=3.3.2
  - asttokens=3.0.0
  - nettle=3.7.3
  - sqlite=3.45.3
  - libcufile=1.9.1.3
  - libgcc=14.2.0
  - jedi=0.19.2
  - python-dateutil=2.9.0.post0
  - ffmpeg=4.3
  - ld_impl_linux-64=2.40
  - mkl=2023.1.0
  - pytorch
  - urllib3=2.3.0
  - jupyter_client=8.6.3
  - libiconv=1.16
  - giflib=5.2.2
  - cuda-nvrtc=11.8.89
  - cuda-cudart=11.8.89
  - certifi
  - _libgcc_mutex=0.1
  - traitlets=5.14.3
  - gnutls=3.6.15
  - libcusparse=11.7.5.86
  - cuda-cupti=11.8.87
  - ncurses=6.4
  - tk=8.6.14
  - openh264=2.1.1
  - krb5=1.21.3
  - prompt-toolkit=3.0.48
  - libuuid=1.41.5
  - cuda-libraries=11.8.0
  - libffi=3.4.4
  - ipykernel=6.29.5
  - parso=0.8.4
  - setuptools=75.1.0
  - libdeflate=1.22
  - wheel=0.44.0
  - psutil=5.9.0
  - bzip2=1.0.8
  - typing_extensions=4.12.2
  - six=1.17.0
  - debugpy=1.8.11
  - pexpect=4.9.0
  - pip=24.2
  - tzdata=2024b
  - ptyprocess=0.7.0
  - zlib=1.2.13
  - executing=2.1.0
  - ca-certificates
  - libstdcxx=14.2.0
  - wcwidth=0.2.13
  - tbb=2021.8.0
  - mkl-service=2.4.0
  - nest-asyncio=1.6.0
  - openssl
  - libedit=3.1.20230828
  - importlib-metadata=8.5.0
  - cuda-nvtx=11.8.86
  - libunistring=0.9.10
  - libsodium=1.0.20
  - libwebp-base=1.3.2
  - torchtriton=3.1.0
  - readline=8.2
  - jpeg=9e
  - zipp=3.21.0
  - libgomp=14.2.0
  - libpng=1.6.39
  - libtiff=4.5.1
  - lerc=4.0.0
  - pytorch-mutex=1.0
  - stack_data=0.6.3
  - pysocks=1.7.1
  - mkl_random=1.2.8
  - matplotlib-inline=0.1.7
  - python=3.12.8
  - networkx=3.4.2
  - xz=5.4.6
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - requests=2.32.3
  - libwebp=1.3.2
  - gmp=6.2.1
  - libtasn1=4.19.0
  - pytorch-cuda=11.8
  - mpmath=1.3.0
  - libnvjpeg=11.9.0.86
  - pygments=2.19.1
  - decorator=5.1.1
  - libcublas=11.11.3.6
  - pyzmq=26.2.0
  - jupyter_core=5.7.2
  - libjpeg-turbo=2.0.0
  - libmpdec=4.0.0
  - packaging=24.2
  - brotli-python=1.0.9
  - lame=3.100
  - pyyaml=6.0.2
  - torchvision
  - torchaudio
  - pandas
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - attrs==24.3.0
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - lightning==2.5.0.post0
      - lightning-utilities==0.11.9
      - matplotlib==3.10.0
      - multidict==6.1.0
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - propcache==0.2.1
      - protobuf==6.30.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyparsing==3.2.1
      - pytorch-lightning==2.5.0.post0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sympy==1.13.1
      - torchmetrics==1.6.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - wandb==0.19.11
      - yarl==1.18.3
